### ISSUE TITLE
Extract language from the buffer's major-mode

### ISSUE THREAD

**Issue by anmoljagetia** [davep/cheat-sh.el#1]
Hey,

Thank you for this cool package. I have recently moved from vim to emacs and the journey has been great. I have used cheat.sh quite extensively and I miss this functionality on emacs until I found your package. 

In vim, the main function automatically identified which programming language was used here primarily by looking at the file extension. Here I always have to type that first before my query: like python read file. I want to ask you if you could implement the function to figure out which language is primarily used by looking at the major mode?

Thank you. I would have contributed this feature, however, my ELisp foo is pretty poor. Thank you very much for your consideration.

Thank you

Best,
Anmol

**Comment by davep** [comment]
I did have a talk (via twitter DM, it seems) about this with the author of cheat.sh about a year ago. The issue is that there needs to be a sensible central mapping of modes to languages on cheat.sh and, I think, it was left that cheat.sh itself would provide that and that editors could call on it. I'm not sure if that was ever added.

Here's what I wrote at the time:

> Having a very quick look at this right now and I'm liking the idea. One small issue I see though is that there doesn't seem to be a simple way of knowing what languages are supported and so it's not obvious to me how I'd let people know that results are available or not. Moreover, I imagine there'd need to be some sort of Emacs major mode name to cheat.sh language name mapping.

> Have you given any thought to, perhaps, allowing the mapping to take place on the server side? That way, if a new language is added to cheat.sh, a client will "just work". Eg: even with Emacs lisp, you get elisp-mode and lisp-interaction-mode. There's more than one major mode people use for JavaScript, etc. If the client could announce to the server "I'm GNU Emacs, and the programming mode I'm in right now is...", it could then give an answer in context.

> Meanwhile, cheat-sh.el does sort of support these sorts of queries as it stands (albeit not as well as it could). M-x cheat-sh RET python/load+a+file RET gets the results you'd expect.

If cheat.sh provides that now it should be doable. Sadly though I can't really guarantee when I'd get time to work on this. My free time for such things is very limited at the moment.

**Comment by anmoljagetia** [comment]
Thank you for your prompt response! According to the docs they have this feature in the vim plugin, so I thought it must be quite possible to do. I would love to help you out (maybe even send a PR) but I really have no idea how to go about this. Can we do something dumb to start-out, like look at the file extension of the buffer and figure out the language (I know this will break between say Python and Python3) or maybe when someone is in a combination situation (like the web-mode), but it does result in less typing so I think it's a good thing.

If you could help me get started, I would love to contribute and help in anyways I can. Thank you once again for this awesome package! Cheers!

**Comment by anmoljagetia** [comment]
I did comeup with something, but it doesn't seem to be working.
I guess your feedback might be extremely helpful on the same.

```elisp
;;;###autoload
(defun cheat-sh-buffer-search (thing)
  "Search `http://cheat.sh/' for something from the buffer"
  (interactive "sSearch: ")
  (let ((value value))
    (cond ((eql major-mode '"python-mode") (setq lang "python"))
          ((eql major-mode '"web-mode") (setq lang "js"))
          ((eql major-mode '"go-mode") (setq lang "go"))
          ((eql major-mode '"emacs-lisp-mode") (setq lang "elisp"))
          ))
  (cheat-sh (concat lang "/" thing)))

```

**Comment by davep** [comment]
Again, I think the correct way to do this is to have cheat.sh handle the mapping. Building it into the Emacs code means it has to be updated any and every time some new language (or other context) is added to cheat.ch. I really think it makes a lot more sense for cheat.sh to accept being told what the client is, and what the context is ("I'm coming from Emacs and the user asked the question while in julia-mode"), as that means everyone benefits any time new stuff is added to cheat.sh without needing to upgrade their copy of the Emacs (or vim, or Atom, or VSCode, or...) client application.

**Comment by anmoljagetia** [comment]
Apologies for the late reply! Have been away for some work issues.

I fully agree with your take on this. The server handds-out this information and everyone benefits from that. Have you have the chance to run this by the people who maintain cheat.sh? Is this an expected feature in any of the upcoming releases? Also, what is a nice "hacky" work-around meanwhile?

I have tried other variants of similar code but have not been able to get the function that I have posted above to work properly :(
Would you be able to help me with this hacky workaround?

**Comment by davep** [comment]
> Have you have the chance to run this by the people who maintain cheat.sh?

[See above](https://github.com/davep/cheat-sh.el/issues/1#issuecomment-491786775).

I'll try and throw together some sort of workaround in a moment. As it stands, I don't really have much time available to dedicate to this code and I never really use it myself so I'm very seldom working with it.

**Comment by davep** [comment]
Perhaps [something like this](https://github.com/davep/cheat-sh.el/commit/22713c912b5665a580effdd6ca877a2d3de7c138) is what you're after? This change creates a framework in which `cheat-sh-guess-topic` can try and guess the topic for you based on the current `major-mode`. Setting up the `major-mode`/topic mapping can be done by using Emacs' customisation system to customise `cheat-sh-topic-mode-map`.

You'll find the whole thing in the [`language-sensitive` branch](https://github.com/davep/cheat-sh.el/tree/language-sensitive) for now.

**Comment by anmoljagetia** [comment]
Hey,

Thank you for this brilliant patch! Thanks a lot for taking this up on priority as well. I am facing another issue here though :( 
I can't seem to get it to work, as in, if I use the `cheat-sh-search-topic function` that uses the new function that you wrote, it doesn't automatically detect the mode (but it gives me a list of suggestions) and when I do end up searching and entering the required text, it shows a blank buffer. 

I have attached a GIF here to demo what I am seeing.
![ScreenRecording20190520at4](https://user-images.githubusercontent.com/6505326/58016493-61ffd380-7b1b-11e9-90df-fa71cd74fe42.gif)

**Comment by davep** [comment]
In the above gif I'm seeing it guess and suggest that the topic is `python` and you appear to be using `python-mode`; that would appear to be correct.

**Comment by davep** [comment]
As for the blank buffer, if I try and `cheat-sh-search-topic`, use `python` as the type, and search `open a file` I get the following from cheat.sh itself:

```html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>
```

I'm afraid I don't have any time to look into this further right at the moment, but this seems to be an issue with cheat.sh itself. Or perhaps the way cheat.sh works regarding topic searching has changed since I wrote this code.

**Comment by anmoljagetia** [comment]
Thank you. This helps a lot in any case. It would be great if you could revisit this when you have time. Once again, Thank you very much for the super cool work!

Cheers!

**Comment by anmoljagetia** [comment]
I think I have found the error. If I remove the `~` on this [line](https://github.com/davep/cheat-sh.el/blob/language-sensitive/cheat-sh.el#L209), it starts to work as expected!

Should I send a PR (Although should only be  one push for you as well). Thanks a lot for this once again!

**Comment by davep** [comment]
Good catch. If I recall correctly that was part of how the topic search worked, so I imagine it's changed at some point. I'll double-check that soon and push up a fix.

**Comment by davep** [comment]
I've made the change in 4b29b3e7be0eadeddc8424b327cb2a2726f751f4 -- hopefully this has it all working. If this all works well and makes sense I'll see about pulling this into master.

**Comment by davep** [comment]
Seeing as how there's been no feedback on this since May, I'm going to assume it's working fine and pull it into master.

**Comment by anmoljagetia** [comment]
Yes, this works good now! Thanks!
