### ISSUE TITLE
cheat-sh-search: query separator has changed

### ISSUE THREAD

**Issue by vpxyz** [davep/cheat-sh.el#5]
currently the separator for queries is '+' , below the quick fix.

` (defun cheat-sh-search (thing)
  "Search for THING on cheat.sh and display the result."
  (interactive "sSearch: ")
  (cheat-sh (concat "+" thing)))
`

**Comment by davep** [comment]
Thanks. You might want to ping cheat.sh and let them know their documentation is out of date, if I'm reading things correctly: http://cheat.sh/:intro
